[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
]

[env]
# TERM = "xterm-256color"

[window]
dimensions = { columns = 150, lines = 40 }
padding = { x = 0, y = 0 }
# decorations = "None"
opacity = 0.7

[scrolling]
multiplier = 5

[font]
normal = { family = "Blex Mono Nerd Font" }
size = 10.5

[cursor]
style = { shape = "Block", blinking = "On" }

[mouse]
hide_when_typing = true
bindings = [{ mouse = "Right", action = "Paste" }]

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
{ key = "Enter", mods = "Alt", action = "ToggleMaximized" },
{ key = "F11", action = "ToggleFullscreen" },
{ key = "W", mods = "Control|Shift", action = "Quit" },
{ key = "PageUp", action = "ScrollPageUp" },
{ key = "PageDown", action = "ScrollPageDown" },
{ key = "+", mods = "Control|Shift", action = "ResetFontSize"},
]
