console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[secondary_prompt]
  template = '❯❯ '
  foreground = 'magenta'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}magenta{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'plain'
    template = '{{ if .WSL }}WSL at {{ end }}{{.Icon}} '
    foreground = 'blue'
    background = 'transparent'
    type = 'os'

  [[blocks.segments]]
    style = 'plain'
    foreground = '#ffff66'
    background = 'transparent'
    type = 'root'

  [[blocks.segments]]
    style = 'plain'
    template = '{{ .Path }} '
    foreground = '#Ff007f'
    background = 'transparent'
    type = 'path'

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    style = 'plain'
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }} '
    foreground = 'yellow'
    background = 'transparent'
    type = 'git'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#ffeb95{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#c5e478{{ end }}', '{{ if gt .Ahead 0 }}#C792EA{{ end }}', '{{ if gt .Behind 0 }}#C792EA{{ end }}']

    [blocks.segments.properties]
      branch_icon = ' '
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    style = 'plain'
    template = '❯'
    background = 'transparent'
    type = 'text'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}magenta{{end}}']

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    style = 'plain'
    template = '{{ .FormattedMs }} '
    foreground = 'yellow'
    background = 'transparent'
    type = 'executiontime'

    [blocks.segments.properties]
      threshold = 5000

  [[blocks.segments]]
    style = 'plain'
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#FFDE57'
    background = 'transparent'
    type = 'python'

    [blocks.segments.properties]
      display_mode = 'context'
      fetch_version = false

  [[blocks.segments]]
    style = 'plain'
    template = '   {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#1E9748'
    background = 'transparent'
    type = 'cmake'

  [[blocks.segments]]
    style = 'plain'
    template = '  {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} '
    foreground = '#6CA35E'
    type = 'node'

    [blocks.segments.properties]
      fetch_package_manager = true
      npm_icon = '<#cc3a3a></>'
      yarn_icon = '<#348cba></>'

  [[blocks.segments]]
    style = 'plain'
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#DF5700'
    type = 'java'

  [[blocks.segments]]
    style = 'plain'
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#0073E6'
    type = 'lua'

  [[blocks.segments]]
    style = 'plain'
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#7FD5EA'
    type = 'go'

  [[blocks.segments]]
    style = 'plain'
    template = '{{ if .SSHSession }} {{ end }}{{ .UserName }}@{{ .HostName }}'
    foreground = 'cyan'
    background = 'transparent'
    type = 'session'
